version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loja_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - loja_network

  nginx:
    image: nginx:alpine
    container_name: loja_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - loja_network

  mysql:
    image: mysql:8.0
    container_name: loja_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loja
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: loja_password
      MYSQL_USER: loja_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - loja_network

networks:
  loja_network:
    driver: bridge

volumes:
  mysql_data:
